# tibco/mashling
FROM golang:1.9.0-alpine3.6
MAINTAINER Jeffrey Bozek, jbozek@tibco.com

RUN go get github.com/constabulary/gb/...
RUN go get github.com/TIBCOSoftware/flogo-cli/...
RUN go get github.com/TIBCOSoftware/flogo-lib/...
RUN go get github.com/TIBCOSoftware/flogo-contrib/...
RUN go get github.com/TIBCOSoftware/mashling/...

RUN mkdir /builds/
WORKDIR /builds/
